### ISSUE TITLE
Proposal : CI workflow for Node.js based applications

### ISSUE THREAD

**Issue by Oza94** [metro-digital-inner-source/.github#14]
Based on our workflow defined here : https://github.com/metro-digital-inner-source/gerland-backend/blob/522c43c79f689a3dab6fb92f72745d7af8452a9c/.github/workflows/ci.yaml

This workflow includes : 

- Node.js dependencies installation with proper caching
- A lint job
- A test job
- A build job
- A sonarqube job that collects coverage from the test job

If this makes sens to you to include this template in the organisation templates, I can make a PR.

Regards,

**Comment by KhrysGabuzian** [comment]
we need two 'spaces' of ci ^^ https://github.com/metro-digital-inner-source/preco-front/blob/develop/.github/workflows/ci.yaml 

- A commit lint job
- A check secrets job
- A Node.js dependencies installation with proper caching
- A lint job

**Comment by Oza94** [comment]
@KhrysGabuzian we can add the "check secrets" job to the template and add appropriate comments to help users determine if the job is relevant for their project !

Also some commands may vary depending on the used tooling (e.g. test runner). Some comments to highlight the key points would be useful 😊 

Edit : for commitlint & secrets, this is not specific to Node.js projects. It may be interesting to have dedicated templates to separate concerns ?

**Comment by PatrykBruder** [comment]
Related #15

**Comment by uwehdaub** [comment]
Closed because of inactivity.
If you are still interested to have this as a template for e.g. MCC France, than create a PR and we can discuss in the PR.
