### ISSUE TITLE
Create a NPM publish workflow template

### ISSUE THREAD

**Issue by pavishenoy-metro** [metro-digital-inner-source/.github#15]
**As a** developer using GitHub
**I would like** to use a Github workflow template to push NPM artifacts to Nexus
**so that it** is easier & faster for me to automize publishing of NPM artifacts to DX Nexus

**Comment by pavishenoy-metro** [comment]
Existing issue to achieve this: https://github.com/metro-digital-inner-source/.github/issues/9

**Comment by uwehdaub** [comment]
Not needed. See #9
