### ISSUE TITLE
Create a GitHub template to publish npm artifacts to DX nexus

### ISSUE THREAD

**Issue by pavishenoy-metro** [metro-digital-inner-source/.github#9]
There are many teams publishing npm artifacts to DX nexus. It would be nice to have a GitHub template that they could simply search and use rather than copy pasting the workflows from existing repositories.

**Comment by blazej-budzynski** [comment]
Looking at OMA's workflow that does this (https://github.com/metro-digital-inner-source/scripted-datasource-plugin/blob/master/.github/workflows/main.yml) I'm not really sure how the template should work. There is many project-specific information there (name of the artifact, name of the team), even versioning, so "simple" with blanks to fill in and adjustments to be made might be more difficult to handle than copy-paste.

**Comment by siilarsi** [comment]
@blazej-budzynski I think we might be able to parameterize that information with the exception of the version. 
The version we could get from `npm version` (https://docs.npmjs.com/cli/v7/commands/npm-version) which we could also utilize to bump the version with.

**Comment by uwehdaub** [comment]
We never got any requests from development teams in the last 18 months.
So creating these kind of workflows don't seem to be a problem, which needs to be solved by us (2tier).
